sets={22,1,2,3,1}
# print(type(sets))
# print(len(sets))
print(sets)
sets.remove(3)
print(sets.pop())
print(sets)
print(sets.pop())
print(sets)
print(sets.pop())
print(sets)
sets.clear()

print(sets.union({4,5,6,4}))
print(sets.intersection({22,2,1,9,0,9}))